# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

input {
  kb_layout = us,ru
  kb_options = grp:alt_shift_toggle
}

# Heavily reduce blur without disabling it entirely.
decoration {
  blur {
    enabled = true
    xray = false
    size = 1
    passes = 1
    brightness = 1
    noise = 0
    contrast = 0.98
    vibrancy = 0.05
    vibrancy_darkness = 0.1
  }
}
