#!/usr/bin/env bash

QUICKSHELL_CONFIG_NAME="ii"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
CONFIG_DIR="$XDG_CONFIG_HOME/quickshell/$QUICKSHELL_CONFIG_NAME"
CACHE_DIR="$XDG_CACHE_HOME/quickshell"
STATE_DIR="$XDG_STATE_HOME/quickshell"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

term_alpha=100 #Set this to < 100 make all your terminals transparent
# sleep 0 # idk i wanted some delay or colors dont get applied properly
if [ ! -d "$STATE_DIR"/user/generated ]; then
  mkdir -p "$STATE_DIR"/user/generated
fi
cd "$CONFIG_DIR" || exit

colornames=''
colorstrings=''
colorlist=()
colorvalues=()

colornames=$(cat $STATE_DIR/user/generated/material_colors.scss | cut -d: -f1)
colorstrings=$(cat $STATE_DIR/user/generated/material_colors.scss | cut -d: -f2 | cut -d ' ' -f2 | cut -d ";" -f1)
IFS=$'\n'
colorlist=($colornames)     # Array of color names
colorvalues=($colorstrings) # Array of color values

apply_term() {
  # Check if terminal escape sequence template exists
  if [ ! -f "$SCRIPT_DIR/terminal/sequences.txt" ]; then
    echo "Template file not found for Terminal. Skipping that."
    return
  fi
  # Copy template
  mkdir -p "$STATE_DIR"/user/generated/terminal
  cp "$SCRIPT_DIR/terminal/sequences.txt" "$STATE_DIR"/user/generated/terminal/sequences.txt
  # Apply colors
  for i in "${!colorlist[@]}"; do
    sed -i "s/${colorlist[$i]} #/${colorvalues[$i]#\#}/g" "$STATE_DIR"/user/generated/terminal/sequences.txt
  done

  sed -i "s/\$alpha/$term_alpha/g" "$STATE_DIR/user/generated/terminal/sequences.txt"

  apply_kitty_from_sequences
  kitty @ --to unix:"$XDG_RUNTIME_DIR/kitty" set-colors -a -c "${XDG_CONFIG_HOME:-$HOME/.config}/kitty/colors.generated.conf" >/dev/null 2>&1 || true

  for file in /dev/pts/*; do
    if [[ $file =~ ^/dev/pts/[0-9]+$ ]]; then
      {
      cat "$STATE_DIR"/user/generated/terminal/sequences.txt >"$file"
      } & disown || true
    fi
  done
}

apply_kitty_from_sequences() {
  local seq="$STATE_DIR/user/generated/terminal/sequences.txt"
  local out="${XDG_CONFIG_HOME:-$HOME/.config}/kitty/colors.generated.conf"

  [ -f "$seq" ] || return 0
  mkdir -p "$(dirname "$out")"

  awk -v esc="$(printf '\033')" '
    function norm(c) {
      gsub(/\r/, "", c)
      gsub(/^[[:space:]]+/, "", c)
      gsub(/[[:space:]]+$/, "", c)
      gsub(/^\[[0-9]+\]/, "", c)     # strip bracketed metadata like [100]#RRGGBB
      if (c ~ /^rgb:/) { sub(/^rgb:/, "", c); gsub(/\//, "", c); c="#" c }
      return c
    }
    BEGIN { print "# Generated by quickshell applycolor.sh - do not edit" }
    {
      if (match($0, esc "\\]10;([^\\a\\x1b\\\\]+)", m)) fg=norm(m[1])
      if (match($0, esc "\\]11;([^\\a\\x1b\\\\]+)", m)) bg=norm(m[1])
      if (match($0, esc "\\]12;([^\\a\\x1b\\\\]+)", m)) cu=norm(m[1])

      s=$0
      while (match(s, esc "\\]4;([0-9]+);([^\\a\\x1b\\\\]+)", m)) {
        idx=m[1]; col=norm(m[2]); pal[idx]=col
        s=substr(s, RSTART+RLENGTH)
      }
    }
    END {
      if (bg!="") print "background " bg
      if (fg!="") print "foreground " fg
      if (cu!="") print "cursor " cu
      for (i=0; i<16; i++) if (pal[i]!="") print "color" i " " pal[i]
    }
  ' "$seq" > "$out"
}

apply_qt() {
  sh "$CONFIG_DIR/scripts/kvantum/materialQT.sh"          # generate kvantum theme
  python "$CONFIG_DIR/scripts/kvantum/changeAdwColors.py" # apply config colors
}

# Check if terminal theming is enabled in config
CONFIG_FILE="$XDG_CONFIG_HOME/illogical-impulse/config.json"
if [ -f "$CONFIG_FILE" ]; then
  enable_terminal=$(jq -r '.appearance.wallpaperTheming.enableTerminal' "$CONFIG_FILE")
  if [ "$enable_terminal" = "true" ]; then
    apply_term &
  fi
else
  echo "Config file not found at $CONFIG_FILE. Applying terminal theming by default."
  apply_term &
fi

# apply_qt & # Qt theming is already handled by kde-material-colors
